# Generated by Django 4.2 on 2023-06-10 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_boleta_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='fecha',
            field=models.DateTimeField(default='2023-06-10 00:48:47'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='dia',
            field=models.DateField(),
        ),
    ]
